version: '3.7'

services:
  db:
    env_file:
      - .env
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=go_campaigns
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d go_campaigns -U postgres"]
      timeout: 10s
      interval: 5s
      retries: 10
  db.migrations:
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    image: db.migrations
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/go_campaigns?sslmode=disable up"
#  server:
#    depends_on:
#      - db.migrations
#    env_file:
#      - .env
#    build: .
#    ports:
#      - "3001:3000"
#    restart: on-failure
